DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'DIRECCION_PEDIDO'
    AND COLUMN_NAME = 'ES_PREDETERMINADA';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DIRECCION_PEDIDO ADD ES_PREDETERMINADA NUMBER(1) DEFAULT 0';
    END IF;
END;
/
