CREATE OR REPLACE PROCEDURE SP_PROCESAR_PAGO (
    p_id_venta IN NUMBER,
    p_metodo IN NUMBER,
    p_monto IN NUMBER
)
AS
BEGIN
    INSERT INTO PAGO (
        ID_PAGO,
        ID_VENTA,
        ID_METODO,
        MONTO,
        FECHA
    )
    VALUES (
        SEQ_PAGO.NEXTVAL,
        p_id_venta,
        p_metodo,
        p_monto,
        SYSTIMESTAMP
    );

    COMMIT;
END;
/

CREATE OR REPLACE TRIGGER TRG_PAGO_COMPLETADO
AFTER INSERT ON PAGO
FOR EACH ROW
BEGIN
    UPDATE PEDIDO
    SET ID_ESTADO = 2
    WHERE ID_VENTA = :NEW.ID_VENTA
    AND ID_ESTADO = 1;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
    WHERE CONSTRAINT_NAME = 'UK_PAGO_VENTA'
    AND TABLE_NAME = 'PAGO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAGO ADD CONSTRAINT UK_PAGO_VENTA UNIQUE (ID_VENTA)';
    END IF;
END;
/

CREATE OR REPLACE VIEW V_PEDIDOS_USUARIO AS
SELECT
    p.ID_PEDIDO,
    v.FECHA,
    v.TOTAL,
    e.NOMBRE AS ESTADO,
    v.ID_USUARIO
FROM PEDIDO p
JOIN VENTA v ON p.ID_VENTA = v.ID_VENTA
JOIN ESTADO_PEDIDO e ON p.ID_ESTADO = e.ID_ESTADO;
/
