-- Complemento de objetos Oracle para mover reglas CRUD a la base de datos.
-- Ejecutar por partes en SQL Developer / SQLcl.
-- Nota: los SELECT no se manejan con triggers; para visualizar se usan VIEWS/FUNCTIONS.

--------------------------------------------------------------------------------
-- 1. SECUENCIAS
--------------------------------------------------------------------------------

DECLARE
    PROCEDURE crear_seq(p_nombre VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = UPPER(p_nombre);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || p_nombre || ' START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
        END IF;
    END;
BEGIN
    crear_seq('SEQ_PERSONA');
    crear_seq('SEQ_USUARIO');
    crear_seq('SEQ_CLIENTE');
    crear_seq('SEQ_PRODUCTO');
    crear_seq('SEQ_PRODUCTO_IMAGEN');
    crear_seq('SEQ_CARRITO');
    crear_seq('SEQ_DETALLE_CARRITO');
    crear_seq('SEQ_DIRECCION_USUARIO');
    crear_seq('SEQ_DIRECCION_PEDIDO');
    crear_seq('SEQ_VENTA');
    crear_seq('SEQ_DETALLE_VENTA');
    crear_seq('SEQ_PEDIDO');
    crear_seq('SEQ_PAGO');
    crear_seq('SEQ_PASSWORD_RESETS');
    crear_seq('SEQ_METODO_PAGO_USUARIO');
END;
/

--------------------------------------------------------------------------------
-- 2. TRIGGERS BASE: IDs, fechas, defaults y validaciones
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_PERSONA_BI
BEFORE INSERT ON PERSONA
FOR EACH ROW
BEGIN
    IF :NEW.ID_PERSONA IS NULL THEN
        SELECT SEQ_PERSONA.NEXTVAL INTO :NEW.ID_PERSONA FROM DUAL;
    END IF;

    :NEW.CORREO := LOWER(TRIM(:NEW.CORREO));
    :NEW.TELEFONO := REGEXP_REPLACE(:NEW.TELEFONO, '[^0-9]', '');
END;
/

CREATE OR REPLACE TRIGGER TRG_USUARIO_BI
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_USUARIO IS NULL THEN
        SELECT SEQ_USUARIO.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
    END IF;

    :NEW.USERNAME := LOWER(TRIM(:NEW.USERNAME));
    :NEW.ESTADO := NVL(UPPER(TRIM(:NEW.ESTADO)), 'ACTIVO');
END;
/

CREATE OR REPLACE TRIGGER TRG_USUARIO_AI_CLIENTE
AFTER INSERT ON USUARIO
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    IF :NEW.ID_TIPO = 3 THEN
        SELECT COUNT(*) INTO v_count
        FROM CLIENTE
        WHERE ID_PERSONA = :NEW.ID_PERSONA;

        IF v_count = 0 THEN
            INSERT INTO CLIENTE (ID_CLIENTE, ID_PERSONA, FECHA_REGISTRO)
            VALUES (SEQ_CLIENTE.NEXTVAL, :NEW.ID_PERSONA, SYSDATE);
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CLIENTE_BI
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENTE IS NULL THEN
        SELECT SEQ_CLIENTE.NEXTVAL INTO :NEW.ID_CLIENTE FROM DUAL;
    END IF;

    :NEW.FECHA_REGISTRO := NVL(:NEW.FECHA_REGISTRO, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTO_BI
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PRODUCTO IS NULL THEN
        SELECT SEQ_PRODUCTO.NEXTVAL INTO :NEW.ID_PRODUCTO FROM DUAL;
    END IF;

    :NEW.ESTADO := NVL(:NEW.ESTADO, 'Activo');
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTO_BU
BEFORE UPDATE ON PRODUCTO
FOR EACH ROW
BEGIN
    IF :NEW.PRECIO < 0 THEN
        RAISE_APPLICATION_ERROR(-20101, 'El precio no puede ser negativo');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTO_IMAGEN_BI
BEFORE INSERT ON PRODUCTO_IMAGEN
FOR EACH ROW
BEGIN
    IF :NEW.ID_IMAGEN IS NULL THEN
        SELECT SEQ_PRODUCTO_IMAGEN.NEXTVAL INTO :NEW.ID_IMAGEN FROM DUAL;
    END IF;

    :NEW.ORDEN := NVL(:NEW.ORDEN, 1);
END;
/

CREATE OR REPLACE TRIGGER TRG_CARRITO_BI
BEFORE INSERT ON CARRITO
FOR EACH ROW
BEGIN
    IF :NEW.ID_CARRITO IS NULL THEN
        SELECT SEQ_CARRITO.NEXTVAL INTO :NEW.ID_CARRITO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DETALLE_CARRITO_BI
BEFORE INSERT ON DETALLE_CARRITO
FOR EACH ROW
BEGIN
    IF :NEW.ID_DETALLE IS NULL THEN
        SELECT SEQ_DETALLE_CARRITO.NEXTVAL INTO :NEW.ID_DETALLE FROM DUAL;
    END IF;

    :NEW.SELECCIONADO := NVL(:NEW.SELECCIONADO, 1);

    IF :NEW.CANTIDAD <= 0 THEN
        RAISE_APPLICATION_ERROR(-20102, 'La cantidad del carrito debe ser mayor a cero');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DETALLE_CARRITO_BU
BEFORE UPDATE ON DETALLE_CARRITO
FOR EACH ROW
BEGIN
    IF :NEW.CANTIDAD <= 0 THEN
        RAISE_APPLICATION_ERROR(-20103, 'La cantidad del carrito debe ser mayor a cero');
    END IF;

    :NEW.SELECCIONADO := CASE WHEN NVL(:NEW.SELECCIONADO, 0) = 1 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE TRIGGER TRG_DIRECCION_USUARIO_BI
BEFORE INSERT ON DIRECCION_USUARIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_DIRECCION IS NULL THEN
        SELECT SEQ_DIRECCION_USUARIO.NEXTVAL INTO :NEW.ID_DIRECCION FROM DUAL;
    END IF;

    :NEW.CREATED_AT := NVL(:NEW.CREATED_AT, SYSDATE);
    :NEW.ES_PREDETERMINADA := NVL(:NEW.ES_PREDETERMINADA, 0);
    :NEW.TELEFONO := REGEXP_REPLACE(:NEW.TELEFONO, '[^0-9]', '');
    :NEW.TELEFONO_ALT := REGEXP_REPLACE(:NEW.TELEFONO_ALT, '[^0-9]', '');
END;
/

CREATE OR REPLACE TRIGGER TRG_DIRECCION_UNICA_PREDET
FOR INSERT OR UPDATE OF ES_PREDETERMINADA ON DIRECCION_USUARIO
COMPOUND TRIGGER
    TYPE t_ids IS TABLE OF DIRECCION_USUARIO.ID_DIRECCION%TYPE INDEX BY PLS_INTEGER;
    TYPE t_users IS TABLE OF DIRECCION_USUARIO.ID_USUARIO%TYPE INDEX BY PLS_INTEGER;
    g_ids t_ids;
    g_users t_users;
    g_count PLS_INTEGER := 0;

    AFTER EACH ROW IS
    BEGIN
        IF :NEW.ES_PREDETERMINADA = 1 THEN
            g_count := g_count + 1;
            g_ids(g_count) := :NEW.ID_DIRECCION;
            g_users(g_count) := :NEW.ID_USUARIO;
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
    BEGIN
        FOR i IN 1 .. g_count LOOP
            UPDATE DIRECCION_USUARIO
            SET ES_PREDETERMINADA = 0
            WHERE ID_USUARIO = g_users(i)
              AND ID_DIRECCION <> g_ids(i)
              AND ES_PREDETERMINADA = 1;
        END LOOP;
    END AFTER STATEMENT;
END;
/

CREATE OR REPLACE TRIGGER TRG_DIRECCION_PEDIDO_BI
BEFORE INSERT ON DIRECCION_PEDIDO
FOR EACH ROW
BEGIN
    IF :NEW.ID_DIRECCION_PEDIDO IS NULL THEN
        SELECT SEQ_DIRECCION_PEDIDO.NEXTVAL INTO :NEW.ID_DIRECCION_PEDIDO FROM DUAL;
    END IF;

    :NEW.CREATED_AT := NVL(:NEW.CREATED_AT, SYSDATE);
    :NEW.UPDATED_AT := NVL(:NEW.UPDATED_AT, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRG_DIRECCION_PEDIDO_BU
BEFORE UPDATE ON DIRECCION_PEDIDO
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER TRG_VENTA_BI
BEFORE INSERT ON VENTA
FOR EACH ROW
BEGIN
    IF :NEW.ID_VENTA IS NULL THEN
        SELECT SEQ_VENTA.NEXTVAL INTO :NEW.ID_VENTA FROM DUAL;
    END IF;

    :NEW.FECHA := NVL(:NEW.FECHA, SYSDATE);
    :NEW.SUBTOTAL := NVL(:NEW.SUBTOTAL, 0);
    :NEW.IVA := NVL(:NEW.IVA, 0);
    :NEW.ENVIO := NVL(:NEW.ENVIO, 0);
    :NEW.TOTAL := NVL(:NEW.TOTAL, :NEW.SUBTOTAL + :NEW.IVA + :NEW.ENVIO);
END;
/

CREATE OR REPLACE TRIGGER TRG_DETALLE_VENTA_BI
BEFORE INSERT ON DETALLE_VENTA
FOR EACH ROW
DECLARE
    v_precio PRODUCTO.PRECIO%TYPE;
    v_nombre PRODUCTO.NOMBRE%TYPE;
BEGIN
    IF :NEW.ID_DETALLE IS NULL THEN
        SELECT SEQ_DETALLE_VENTA.NEXTVAL INTO :NEW.ID_DETALLE FROM DUAL;
    END IF;

    SELECT PRECIO, NOMBRE
    INTO v_precio, v_nombre
    FROM PRODUCTO
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    :NEW.PRECIO_UNITARIO := NVL(:NEW.PRECIO_UNITARIO, v_precio);
    :NEW.NOMBRE_PRODUCTO := NVL(:NEW.NOMBRE_PRODUCTO, SUBSTR(v_nombre, 1, 150));
    :NEW.SUBTOTAL := NVL(:NEW.SUBTOTAL, :NEW.CANTIDAD * :NEW.PRECIO_UNITARIO);
END;
/

CREATE OR REPLACE TRIGGER TRG_PEDIDO_BI
BEFORE INSERT ON PEDIDO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PEDIDO IS NULL THEN
        SELECT SEQ_PEDIDO.NEXTVAL INTO :NEW.ID_PEDIDO FROM DUAL;
    END IF;

    :NEW.ID_ESTADO := NVL(:NEW.ID_ESTADO, 1);
END;
/

CREATE OR REPLACE TRIGGER TRG_PAGO_BI
BEFORE INSERT ON PAGO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PAGO IS NULL THEN
        SELECT SEQ_PAGO.NEXTVAL INTO :NEW.ID_PAGO FROM DUAL;
    END IF;

    :NEW.FECHA := NVL(:NEW.FECHA, SYSTIMESTAMP);
    :NEW.ESTADO := NVL(UPPER(TRIM(:NEW.ESTADO)), 'PAGADO');
END;
/

CREATE OR REPLACE TRIGGER TRG_PAGO_AI_ESTADO_PEDIDO
AFTER INSERT OR UPDATE OF ESTADO ON PAGO
FOR EACH ROW
BEGIN
    IF UPPER(TRIM(:NEW.ESTADO)) = 'APPROVED'
       OR (
           UPPER(TRIM(:NEW.ESTADO)) IN ('PAGADO', 'COMPLETADO')
           AND :NEW.ID_TRANSACCION_WOMPI IS NOT NULL
           AND TRIM(TO_CHAR(:NEW.ID_TRANSACCION_WOMPI)) <> ''
       ) THEN
        UPDATE PEDIDO
        SET ID_ESTADO = 2
        WHERE ID_VENTA = :NEW.ID_VENTA
          AND ID_ESTADO IN (1, 5);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PASSWORD_RESETS_BI
BEFORE INSERT ON PASSWORD_RESETS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_PASSWORD_RESETS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;

    :NEW.USED := NVL(:NEW.USED, 0);
    :NEW.EXPIRES_AT := NVL(:NEW.EXPIRES_AT, CURRENT_TIMESTAMP + INTERVAL '1' DAY);
END;
/

--------------------------------------------------------------------------------
-- 3. FUNCIONES
--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION FN_TOTAL_CARRITO(
    p_id_usuario IN NUMBER,
    p_solo_seleccionados IN NUMBER DEFAULT 0
) RETURN NUMBER
AS
    v_total NUMBER(10,2);
BEGIN
    SELECT NVL(SUM(p.PRECIO * dc.CANTIDAD), 0)
    INTO v_total
    FROM CARRITO c
    JOIN DETALLE_CARRITO dc ON dc.ID_CARRITO = c.ID_CARRITO
    JOIN PRODUCTO p ON p.ID_PRODUCTO = dc.ID_PRODUCTO
    WHERE c.ID_USUARIO = p_id_usuario
      AND (p_solo_seleccionados = 0 OR NVL(dc.SELECCIONADO, 0) = 1);

    RETURN v_total;
END;
/

CREATE OR REPLACE FUNCTION FN_TOTAL_VENTA(
    p_id_venta IN NUMBER
) RETURN NUMBER
AS
    v_total NUMBER(10,2);
BEGIN
    SELECT NVL(SUM(SUBTOTAL), 0)
    INTO v_total
    FROM DETALLE_VENTA
    WHERE ID_VENTA = p_id_venta;

    RETURN v_total;
END;
/

CREATE OR REPLACE FUNCTION FN_USUARIO_EXISTE(p_username IN VARCHAR2)
RETURN NUMBER
AS
    v_total NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_total
    FROM USUARIO
    WHERE LOWER(USERNAME) = LOWER(TRIM(p_username));

    RETURN CASE WHEN v_total > 0 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE FUNCTION FN_CORREO_EXISTE(p_correo IN VARCHAR2)
RETURN NUMBER
AS
    v_total NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_total
    FROM PERSONA
    WHERE LOWER(TRIM(CORREO)) = LOWER(TRIM(p_correo));

    RETURN CASE WHEN v_total > 0 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE FUNCTION FN_TELEFONO_EXISTE(p_telefono IN VARCHAR2)
RETURN NUMBER
AS
    v_total NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_total
    FROM PERSONA
    WHERE TELEFONO = REGEXP_REPLACE(p_telefono, '[^0-9]', '');

    RETURN CASE WHEN v_total > 0 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE FUNCTION FN_PEDIDO_PUEDE_CANCELARSE(p_id_pedido IN NUMBER)
RETURN NUMBER
AS
    v_total NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_total
    FROM PEDIDO
    WHERE ID_PEDIDO = p_id_pedido
      AND ID_ESTADO IN (1, 2);

    RETURN CASE WHEN v_total > 0 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE FUNCTION FN_DIRECCION_PREDETERMINADA(p_id_usuario IN NUMBER)
RETURN NUMBER
AS
    v_id DIRECCION_USUARIO.ID_DIRECCION%TYPE;
BEGIN
    SELECT ID_DIRECCION
    INTO v_id
    FROM DIRECCION_USUARIO
    WHERE ID_USUARIO = p_id_usuario
      AND ES_PREDETERMINADA = 1
    FETCH FIRST 1 ROWS ONLY;

    RETURN v_id;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

--------------------------------------------------------------------------------
-- 4. VISTAS DE VISUALIZACION
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW V_USUARIO_COMPLETO AS
SELECT
    u.ID_USUARIO,
    u.ID_PERSONA,
    u.ID_TIPO,
    u.USERNAME,
    u.ESTADO,
    p.NOMBRES,
    p.APELLIDOS,
    p.CORREO,
    p.TELEFONO,
    p.DIRECCION,
    tu.NOMBRE AS TIPO_USUARIO
FROM USUARIO u
JOIN PERSONA p ON p.ID_PERSONA = u.ID_PERSONA
JOIN TIPO_USUARIO tu ON tu.ID_TIPO = u.ID_TIPO;
/

CREATE OR REPLACE VIEW V_PRODUCTOS_ADMIN AS
SELECT
    p.ID_PRODUCTO,
    p.NOMBRE,
    p.CODIGO,
    p.DESCRIPCION,
    p.PRECIO,
    p.ESTADO,
    p.ID_CATEGORIA,
    c.NOMBRE AS CATEGORIA_NOMBRE,
    img.IMAGEN
FROM PRODUCTO p
JOIN CATEGORIA_PRODUCTO c ON c.ID_CATEGORIA = p.ID_CATEGORIA
LEFT JOIN (
    SELECT ID_PRODUCTO,
           MIN(URL) KEEP (DENSE_RANK FIRST ORDER BY NVL(ORDEN, 999999), ID_IMAGEN) AS IMAGEN
    FROM PRODUCTO_IMAGEN
    GROUP BY ID_PRODUCTO
) img ON img.ID_PRODUCTO = p.ID_PRODUCTO;
/

CREATE OR REPLACE VIEW V_CARRITO_USUARIO AS
SELECT
    c.ID_USUARIO,
    c.ID_CARRITO,
    dc.ID_DETALLE,
    dc.ID_PRODUCTO,
    dc.ID_REFERENCIA,
    dc.CANTIDAD,
    NVL(dc.SELECCIONADO, 0) AS SELECCIONADO,
    p.NOMBRE,
    p.PRECIO,
    p.PRECIO * dc.CANTIDAD AS SUBTOTAL
FROM CARRITO c
JOIN DETALLE_CARRITO dc ON dc.ID_CARRITO = c.ID_CARRITO
JOIN PRODUCTO p ON p.ID_PRODUCTO = dc.ID_PRODUCTO;
/

CREATE OR REPLACE VIEW V_DIRECCIONES_USUARIO AS
SELECT
    ID_DIRECCION,
    ID_USUARIO,
    NOMBRE,
    APELLIDO,
    DIRECCION,
    CIUDAD,
    BARRIO,
    TELEFONO,
    TELEFONO_ALT,
    INFO_ADICIONAL,
    NVL(ES_PREDETERMINADA, 0) AS ES_PREDETERMINADA,
    CREATED_AT
FROM DIRECCION_USUARIO;
/

CREATE OR REPLACE VIEW V_DETALLE_PEDIDO AS
SELECT
    pe.ID_PEDIDO,
    pe.ID_ESTADO,
    ep.NOMBRE AS ESTADO,
    v.ID_VENTA,
    v.ID_USUARIO,
    v.FECHA,
    v.SUBTOTAL,
    v.IVA,
    v.ENVIO,
    v.TOTAL,
    dv.ID_PRODUCTO,
    dv.CANTIDAD,
    dv.PRECIO_UNITARIO,
    dv.SUBTOTAL AS SUBTOTAL_PRODUCTO,
    dv.NOMBRE_PRODUCTO
FROM PEDIDO pe
JOIN VENTA v ON v.ID_VENTA = pe.ID_VENTA
JOIN ESTADO_PEDIDO ep ON ep.ID_ESTADO = pe.ID_ESTADO
LEFT JOIN DETALLE_VENTA dv ON dv.ID_VENTA = v.ID_VENTA;
/

CREATE OR REPLACE VIEW V_ADMIN_PEDIDOS AS
SELECT
    p.ID_PEDIDO,
    p.ID_VENTA,
    p.ID_ESTADO,
    e.NOMBRE AS ESTADO,
    v.ID_USUARIO,
    v.FECHA,
    v.TOTAL,
    dp.CIUDAD,
    dp.BARRIO,
    dp.DIRECCION_ENVIO
FROM PEDIDO p
JOIN VENTA v ON v.ID_VENTA = p.ID_VENTA
JOIN ESTADO_PEDIDO e ON e.ID_ESTADO = p.ID_ESTADO
LEFT JOIN DIRECCION_PEDIDO dp ON dp.ID_DIRECCION_PEDIDO = p.ID_DIRECCION_PEDIDO;
/

--------------------------------------------------------------------------------
-- 5. PROCEDIMIENTOS CRUD PRINCIPALES
--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PERFIL (
    p_id_usuario IN NUMBER,
    p_nombres IN VARCHAR2,
    p_apellidos IN VARCHAR2,
    p_correo IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_direccion IN VARCHAR2
)
AS
    v_id_persona NUMBER;
BEGIN
    SELECT ID_PERSONA INTO v_id_persona
    FROM USUARIO
    WHERE ID_USUARIO = p_id_usuario;

    UPDATE PERSONA
    SET NOMBRES = TRIM(p_nombres),
        APELLIDOS = TRIM(p_apellidos),
        CORREO = LOWER(TRIM(p_correo)),
        TELEFONO = REGEXP_REPLACE(p_telefono, '[^0-9]', ''),
        DIRECCION = TRIM(p_direccion)
    WHERE ID_PERSONA = v_id_persona;
END;
/

CREATE OR REPLACE PROCEDURE SP_CAMBIAR_PASSWORD (
    p_id_usuario IN NUMBER,
    p_password_hash IN VARCHAR2
)
AS
BEGIN
    UPDATE USUARIO
    SET PASSWORD = p_password_hash
    WHERE ID_USUARIO = p_id_usuario;
END;
/

CREATE OR REPLACE PROCEDURE SP_CREAR_PRODUCTO (
    p_nombre IN VARCHAR2,
    p_codigo IN NUMBER,
    p_descripcion IN VARCHAR2,
    p_precio IN NUMBER,
    p_estado IN VARCHAR2,
    p_id_categoria IN NUMBER,
    p_id_producto OUT NUMBER
)
AS
BEGIN
    INSERT INTO PRODUCTO (NOMBRE, CODIGO, DESCRIPCION, PRECIO, ESTADO, ID_CATEGORIA)
    VALUES (p_nombre, p_codigo, p_descripcion, p_precio, NVL(p_estado, 'Activo'), p_id_categoria)
    RETURNING ID_PRODUCTO INTO p_id_producto;
END;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PRODUCTO (
    p_id_producto IN NUMBER,
    p_nombre IN VARCHAR2,
    p_codigo IN NUMBER,
    p_descripcion IN VARCHAR2,
    p_precio IN NUMBER,
    p_estado IN VARCHAR2,
    p_id_categoria IN NUMBER
)
AS
BEGIN
    UPDATE PRODUCTO
    SET NOMBRE = p_nombre,
        CODIGO = p_codigo,
        DESCRIPCION = p_descripcion,
        PRECIO = p_precio,
        ESTADO = p_estado,
        ID_CATEGORIA = p_id_categoria
    WHERE ID_PRODUCTO = p_id_producto;
END;
/

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_PRODUCTO (
    p_id_producto IN NUMBER
)
AS
BEGIN
    DELETE FROM PRODUCTO_IMAGEN
    WHERE ID_PRODUCTO = p_id_producto;

    DELETE FROM PRODUCTO
    WHERE ID_PRODUCTO = p_id_producto;
END;
/

CREATE OR REPLACE PROCEDURE SP_GUARDAR_IMAGEN_PRODUCTO (
    p_id_producto IN NUMBER,
    p_url IN VARCHAR2,
    p_orden IN NUMBER
)
AS
BEGIN
    INSERT INTO PRODUCTO_IMAGEN (ID_PRODUCTO, URL, ORDEN)
    VALUES (p_id_producto, p_url, p_orden);
END;
/

CREATE OR REPLACE PROCEDURE SP_AGREGAR_CARRITO (
    p_id_usuario IN NUMBER,
    p_id_producto IN NUMBER,
    p_id_referencia IN NUMBER,
    p_cantidad IN NUMBER
)
AS
    v_id_carrito NUMBER;
    v_id_detalle NUMBER;
BEGIN
    BEGIN
        SELECT ID_CARRITO INTO v_id_carrito
        FROM CARRITO
        WHERE ID_USUARIO = p_id_usuario
        FOR UPDATE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO CARRITO (ID_USUARIO)
            VALUES (p_id_usuario)
            RETURNING ID_CARRITO INTO v_id_carrito;
    END;

    BEGIN
        SELECT ID_DETALLE INTO v_id_detalle
        FROM DETALLE_CARRITO
        WHERE ID_CARRITO = v_id_carrito
          AND ID_PRODUCTO = p_id_producto
          AND ID_REFERENCIA = p_id_referencia
        FOR UPDATE;

        UPDATE DETALLE_CARRITO
        SET CANTIDAD = CANTIDAD + p_cantidad,
            SELECCIONADO = 1
        WHERE ID_DETALLE = v_id_detalle;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO DETALLE_CARRITO (
                ID_CARRITO,
                ID_PRODUCTO,
                ID_REFERENCIA,
                CANTIDAD,
                SELECCIONADO
            ) VALUES (
                v_id_carrito,
                p_id_producto,
                p_id_referencia,
                p_cantidad,
                1
            );
    END;
END;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_CARRITO (
    p_id_usuario IN NUMBER,
    p_id_producto IN NUMBER,
    p_id_referencia IN NUMBER,
    p_cantidad IN NUMBER
)
AS
    v_id_carrito NUMBER;
BEGIN
    SELECT ID_CARRITO INTO v_id_carrito
    FROM CARRITO
    WHERE ID_USUARIO = p_id_usuario;

    UPDATE DETALLE_CARRITO
    SET CANTIDAD = p_cantidad
    WHERE ID_CARRITO = v_id_carrito
      AND ID_PRODUCTO = p_id_producto
      AND ID_REFERENCIA = p_id_referencia;
END;
/

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_CARRITO (
    p_id_usuario IN NUMBER,
    p_id_producto IN NUMBER,
    p_id_referencia IN NUMBER
)
AS
    v_id_carrito NUMBER;
BEGIN
    SELECT ID_CARRITO INTO v_id_carrito
    FROM CARRITO
    WHERE ID_USUARIO = p_id_usuario;

    DELETE FROM DETALLE_CARRITO
    WHERE ID_CARRITO = v_id_carrito
      AND ID_PRODUCTO = p_id_producto
      AND ID_REFERENCIA = p_id_referencia;
END;
/

CREATE OR REPLACE PROCEDURE SP_VACIAR_CARRITO (
    p_id_usuario IN NUMBER
)
AS
    v_id_carrito NUMBER;
BEGIN
    SELECT ID_CARRITO INTO v_id_carrito
    FROM CARRITO
    WHERE ID_USUARIO = p_id_usuario;

    DELETE FROM DETALLE_CARRITO
    WHERE ID_CARRITO = v_id_carrito;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;
/

CREATE OR REPLACE PROCEDURE SP_CANCELAR_PEDIDO (
    p_id_pedido IN NUMBER,
    p_id_usuario IN NUMBER
)
AS
    v_id_estado PEDIDO.ID_ESTADO%TYPE;
BEGIN
    SELECT p.ID_ESTADO
    INTO v_id_estado
    FROM PEDIDO p
    JOIN VENTA v ON v.ID_VENTA = p.ID_VENTA
    WHERE p.ID_PEDIDO = p_id_pedido
      AND v.ID_USUARIO = p_id_usuario
    FOR UPDATE;

    IF v_id_estado IN (3, 4) THEN
        RAISE_APPLICATION_ERROR(-20121, 'El pedido ya esta en camino o fue entregado');
    ELSIF v_id_estado = 5 THEN
        RAISE_APPLICATION_ERROR(-20122, 'Pedido cancelado');
    ELSIF v_id_estado NOT IN (1, 2) THEN
        RAISE_APPLICATION_ERROR(-20120, 'No se puede cancelar el pedido');
    END IF;

    UPDATE PEDIDO
    SET ID_ESTADO = 5
    WHERE ID_PEDIDO = p_id_pedido;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20120, 'No se puede cancelar el pedido');
END;
/

CREATE OR REPLACE PROCEDURE SP_EXPIRAR_PEDIDOS
AS
BEGIN
    UPDATE PEDIDO p
    SET p.ID_ESTADO = 5
    WHERE p.ID_ESTADO = 1
      AND p.CREATED_AT IS NOT NULL
      AND CAST(p.CREATED_AT AS TIMESTAMP) < SYSTIMESTAMP - INTERVAL '5' MINUTE
      AND NOT EXISTS (
          SELECT 1
          FROM PAGO pg
          WHERE pg.ID_VENTA = p.ID_VENTA
            AND UPPER(TRIM(pg.ESTADO)) IN ('APPROVED', 'PAGADO', 'COMPLETADO')
      );
END;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_METODO_PAGO (
    p_id_metodo_pago_usuario IN NUMBER,
    p_id_usuario IN NUMBER,
    p_titular IN VARCHAR2,
    p_fecha_expiracion IN VARCHAR2,
    p_es_predeterminado IN NUMBER
)
AS
BEGIN
    IF NVL(p_es_predeterminado, 0) = 1 THEN
        UPDATE METODO_PAGO_USUARIO
        SET ES_PREDETERMINADO = 0
        WHERE ID_USUARIO = p_id_usuario
          AND ID_METODO_PAGO_USUARIO <> p_id_metodo_pago_usuario;
    END IF;

    UPDATE METODO_PAGO_USUARIO
    SET TITULAR = SUBSTR(TRIM(p_titular), 1, 120),
        FECHA_EXPIRACION = TO_DATE(p_fecha_expiracion, 'MM/YYYY'),
        ES_PREDETERMINADO = CASE WHEN NVL(p_es_predeterminado, 0) = 1 THEN 1 ELSE 0 END
    WHERE ID_METODO_PAGO_USUARIO = p_id_metodo_pago_usuario
      AND ID_USUARIO = p_id_usuario
      AND ACTIVO = 1;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20550, 'Metodo de pago no encontrado');
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_METODO_PAGO (
    p_id_metodo_pago_usuario IN NUMBER,
    p_id_usuario IN NUMBER
)
AS
BEGIN
    UPDATE METODO_PAGO_USUARIO
    SET ACTIVO = 0,
        ES_PREDETERMINADO = 0
    WHERE ID_METODO_PAGO_USUARIO = p_id_metodo_pago_usuario
      AND ID_USUARIO = p_id_usuario;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20551, 'Metodo de pago no encontrado');
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE SP_PREDETERMINAR_METODO_PAGO (
    p_id_metodo_pago_usuario IN NUMBER,
    p_id_usuario IN NUMBER
)
AS
BEGIN
    UPDATE METODO_PAGO_USUARIO
    SET ES_PREDETERMINADO = 0
    WHERE ID_USUARIO = p_id_usuario;

    UPDATE METODO_PAGO_USUARIO
    SET ES_PREDETERMINADO = 1
    WHERE ID_METODO_PAGO_USUARIO = p_id_metodo_pago_usuario
      AND ID_USUARIO = p_id_usuario
      AND ACTIVO = 1;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20552, 'Metodo de pago no encontrado');
    END IF;
END;
/
