-- Secuencias para REFERENCIA_PRODUCTO y tablas de compatibilidad
-- Ejecutar en SQL Developer / SQLcl antes de crear productos desde el admin
-- Este script es idempotente: si las secuencias ya existen no hace nada

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_REFERENCIA_PRODUCTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_COMPATIBILIDAD_VEHICULO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_COMPATIBILIDAD_MAQUINARIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
