-- Secuencias e triggers para REFERENCIA_PRODUCTO y tablas de compatibilidad
-- Ejecutar en SQL Developer / SQLcl (idempotente)

-- Secuencia para REFERENCIA_PRODUCTO
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_REFERENCIA_PRODUCTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Secuencia para COMPATIBILIDAD_VEHICULO
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_COMPATIBILIDAD_VEHICULO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Secuencia para COMPATIBILIDAD_MAQUINARIA
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_COMPATIBILIDAD_MAQUINARIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Trigger para asignar ID_REFERENCIA automaticamente
CREATE OR REPLACE TRIGGER TRG_REFERENCIA_PRODUCTO_BI
BEFORE INSERT ON REFERENCIA_PRODUCTO
FOR EACH ROW
BEGIN
  IF :NEW.ID_REFERENCIA IS NULL THEN
    SELECT SEQ_REFERENCIA_PRODUCTO.NEXTVAL INTO :NEW.ID_REFERENCIA FROM DUAL;
  END IF;
  :NEW.ESTADO := NVL(:NEW.ESTADO, 'Activo');
END;
/

-- Trigger para asignar ID en COMPATIBILIDAD_VEHICULO
CREATE OR REPLACE TRIGGER TRG_COMPAT_VEHICULO_BI
BEFORE INSERT ON COMPATIBILIDAD_VEHICULO
FOR EACH ROW
BEGIN
  IF :NEW.ID_COMPATIBILIDAD_V IS NULL THEN
    SELECT SEQ_COMPATIBILIDAD_VEHICULO.NEXTVAL INTO :NEW.ID_COMPATIBILIDAD_V FROM DUAL;
  END IF;
END;
/

-- Trigger para asignar ID en COMPATIBILIDAD_MAQUINARIA
CREATE OR REPLACE TRIGGER TRG_COMPAT_MAQUINARIA_BI
BEFORE INSERT ON COMPATIBILIDAD_MAQUINARIA
FOR EACH ROW
BEGIN
  IF :NEW.ID_COMPATIBILIDAD_M IS NULL THEN
    SELECT SEQ_COMPATIBILIDAD_MAQUINARIA.NEXTVAL INTO :NEW.ID_COMPATIBILIDAD_M FROM DUAL;
  END IF;
END;
/
