-- Columna ID_REPARTIDOR en PEDIDO (idempotente)
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'PEDIDO' AND COLUMN_NAME = 'ID_REPARTIDOR';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PEDIDO ADD (ID_REPARTIDOR NUMBER(10))';
  END IF;
END;
/

-- Tabla ENTREGA_PEDIDO (idempotente)
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ENTREGA_PEDIDO (
      ID_ENTREGA       NUMBER(10)   PRIMARY KEY,
      ID_PEDIDO        NUMBER(10)   NOT NULL,
      ID_REPARTIDOR    NUMBER(10)   NOT NULL,
      ESTADO_ENTREGA   VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
      FECHA_ASIGNACION DATE         DEFAULT SYSDATE NOT NULL,
      FECHA_ENTREGA    DATE,
      CONSTRAINT FK_EP_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Secuencia para ENTREGA_PEDIDO (idempotente)
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_ENTREGA_PEDIDO START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
