CREATE OR REPLACE VIEW V_COMPATIBILIDADES_VEHICULO AS
SELECT
    P.ID_PRODUCTO,
    P.NOMBRE AS NOMBRE_PRODUCTO,
    RP.NUMERO_REFERENCIA,
    RP.MARCA,
    RP.FABRICANTE,
    CV.MARCA_VEHICULO,
    CV.MODELO_VEHICULO,
    CV.ANO_INICIO,
    CV.ANO_FIN,
    CV.MOTOR,
    CV.TRANSMISION,
    P.PRECIO,
    CV.STOCK_P AS STOCK_TOTAL
FROM PRODUCTO P
INNER JOIN REFERENCIA_PRODUCTO RP ON P.ID_PRODUCTO = RP.ID_PRODUCTO
INNER JOIN COMPATIBILIDAD_VEHICULO CV ON RP.ID_REFERENCIA = CV.ID_REFERENCIA
WHERE UPPER(TRIM(P.ESTADO)) IN ('ACTIVO', 'TRUE')
AND UPPER(TRIM(RP.ESTADO)) IN ('ACTIVO', 'TRUE');
