CREATE OR REPLACE VIEW V_COMPATIBILIDADES_MAQUINARIA AS
SELECT
    P.ID_PRODUCTO,
    P.NOMBRE,
    P.PRECIO,
    CM.TIPO_MAQUINARIA,
    CM.MARCA_MAQUINA,
    CM.MODELO_MAQUINA
FROM PRODUCTO P
JOIN REFERENCIA_PRODUCTO RP ON RP.ID_PRODUCTO = P.ID_PRODUCTO
JOIN COMPATIBILIDAD_MAQUINARIA CM ON CM.ID_REFERENCIA = RP.ID_REFERENCIA
WHERE P.ESTADO = 'true';
