CREATE OR REPLACE VIEW V_COMPATIBILIDADES_MAQUINARIA AS
SELECT
    R.ID_PRODUCTO,
    CM.TIPO_MAQUINARIA,
    CM.MARCA_MAQUINARIA,
    CM.MODELO_MAQUINARIA,
    CM.STOCK_P
FROM COMPATIBILIDAD_MAQUINARIA CM
JOIN REFERENCIA_PRODUCTO R ON R.ID_REFERENCIA = CM.ID_REFERENCIA;
