-- Recrear V_DEVOLUCIONES_ADMIN agregando alias CLIENTE
-- Ejecutar en Oracle SQL Developer / SQLcl contra el esquema de produccion

CREATE OR REPLACE VIEW V_DEVOLUCIONES_ADMIN AS
SELECT
    d.ID_DEVOLUCION,
    d.ID_PEDIDO,
    d.ID_USUARIO,
    d.ID_ESTADO_DEVOLUCION,
    TO_CHAR(d.FECHA_SOLICITUD,  'DD/MM/YYYY HH24:MI') AS FECHA_SOLICITUD,
    TO_CHAR(d.FECHA_APROBACION, 'DD/MM/YYYY HH24:MI') AS FECHA_APROBACION,
    TO_CHAR(d.FECHA_RECEPCION,  'DD/MM/YYYY HH24:MI') AS FECHA_RECEPCION,
    TO_CHAR(d.FECHA_REEMBOLSO,  'DD/MM/YYYY HH24:MI') AS FECHA_REEMBOLSO,
    ed.NOMBRE                                          AS ESTADO_NOMBRE,
    per.NOMBRES,
    per.APELLIDOS,
    per.NOMBRES || ' ' || per.APELLIDOS                AS CLIENTE,
    per.CORREO,
    NVL(d.REEMBOLSO_REALIZADO, 0)                      AS REEMBOLSO_REALIZADO,
    d.REEMBOLSO_ESTADO,
    d.REEMBOLSO_ID_WOMPI
FROM DEVOLUCION d
INNER JOIN ESTADO_DEVOLUCION ed  ON ed.ID_ESTADO_DEVOLUCION = d.ID_ESTADO_DEVOLUCION
INNER JOIN USUARIO u             ON u.ID_USUARIO            = d.ID_USUARIO
INNER JOIN PERSONA per           ON per.ID_PERSONA          = u.ID_PERSONA;
/
